name: Frontend CI

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Calculate version
      id: version
      run: |
        latest_tag=$(git describe --tags --abbrev=0 --match "frontend-v*" 2>/dev/null || echo "frontend-v0.1.0")
        current_version=${latest_tag#frontend-v}
        IFS='.' read -r major minor patch <<< "$current_version"
        new_patch=$((patch + 1))
        new_version="v$major.$minor.$new_patch"
        echo "new_version=$new_version" >> $GITHUB_OUTPUT
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: frontend
        push: true
        tags: |
          thabelo/quotes-frontend:latest
          thabelo/quotes-frontend:${{ steps.version.outputs.new_version }}
        cache-from: type=registry,ref=thabelo/quotes-frontend:buildcache
        cache-to: type=registry,ref=thabelo/quotes-frontend:buildcache,mode=max

    - name: Create and push git tag
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git tag frontend-${{ steps.version.outputs.new_version }}
        git push origin frontend-${{ steps.version.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}